### ISSUE TITLE
Scrolling tooltips hard to scroll sometimes

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#25]
When hovering over a tcl proc call, a tooltip will appear with the proc's documentation comment. Often this is too long, so some IDEs make a scrollable tooltip. The problem is that often we have multi-line proc calls, like this:

```
my-awesome-proc \
   "this is a
    really long arg" \
   "some other arg" \
   "so many args"
```

If this is near the top of the screen, VS Code at least will make the tooltip appear under this call (so the mouse pointer is not adjacent to the tooltip). If you move the mouse to get into the tooltip to scroll it, the tooltip disappears.

The workaround appears to be to move the proc call lower on the screen so the tooltip appears above it, and then you can mouse into it just fine.

Perhaps tooltip behavior can be customized to either allow the tooltip to cover the args, or else to not disappear immediately so the mouse has a chance to get into it?

**Comment by adeschamps** [comment]
The response to a hover request ([see `Hover`](https://microsoft.github.io/language-server-protocol/specification#textDocument_hover)) includes a `range` field that indicates the span of the thing being hovered over. In our implementation, the span includes the proc name and all its arguments, which is why VSCode puts the tooltip above or below the entire proc call.

It probably makes sense to just indicatet the span of the proc name, in which case the tooltip would show up immediately below the `my-awesome-proc` line.
