### ISSUE TITLE
Ignore whitespace separating proc definition from comments

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#26]
Sometimes procs are defined with comment blocks that are separated from the proc start by whitespace. For example, this is in NGS3:

```
# start a production to bind to an active goal with a given most derived type
#
# e.g. sp "my-production
#          [NGS_match-active-goal myGoalType <goal-bind> ]
#          -->
#          ...do something...
#
# @devnote There's a slight danger of conflict here in using the hardcoded "<s>" as the state's ID - 
#          but <s> is such a convention in the soar community that it's unlikely to be 
#          anything else.

proc NGS_match-active-goal { goal_type 
                               {goal_bind ""} 
                               {state_bind <s>} } {
  variable active_goal

  # Default value initialization
  if {$goal_bind == ""} {set goal_bind [NGS_gen-soar-varname "bound-goal"]}

  return "(state $state_bind ^superstate   nil
                             ^$active_goal $goal_bind)
          [NGS_is-most-derived-type $goal_bind $goal_type]"
}
```

Currently the comment block isn't "seen" because of the whitespace separation, so the hover tooltip just shows the name of the proc and none of the useful documentation.

**Comment by adeschamps** [comment]
I would consider this an issue in NGS which should be fixed.

In general, it's difficult to determine which item a comment should be associated with (which is why some languages have multiple syntaxes for comments in order to disambiguate this). For example, if there's a comment block at the top of a file, is it describing the entire file, or the first proc?

**Comment by marinier** [comment]
I think that is an unrealistic expectation. NGS 3 hasn't been touched in years, but it's present in the vast majority of existing SoarTech Soar code -- usually just copied into the project, so even if you were to update the version on github, most existing agents would remain broken wrt this functionality.

I wouldn't worry about ambiguities -- the old Soar IDE doesn't, and no one has ever complained about this.

I think maybe the trick is to only ignore the whitespace between the proc and the first comment block. If above that there is more whitespace and then more comments, those are not included. While a comment block at the top of the file could get associated with the first proc this way, it's also easy to fix by adding actual comments on that proc -- which should be there anyway.

**Comment by adeschamps** [comment]
Ignoring whitespace would also lead to false positives in cases where groups of procedures are separated by comment blocks, such that the comment block semantically belongs to the group rather than the first item.

I'd rather not add special cases supporting things that aren't specified by the language.

**Comment by adeschamps** [comment]
In talking with Bob, we decided to optimize for utility over strictness, so I'm going to implement his suggestion. Soar and Tcl don't have the strong conventions or multiple comment syntaxes that are necessary to unambiguously associate comments with a particular item anyway.
