### ISSUE TITLE
TCL Expansion

### ISSUE THREAD

**Issue by rpicking** [soartech/soar-language-server#33]
Tcl expansion is currently implemented by adding a hyperlink for all Productions found in the file analysis.  The link is placed on the first normal_word child.  The link will take you to the `buffer.soar` file that is created at the root of the current workspace.  The `buffer.soar` file is populated with expanded soar code when you hover over a production.

It is currently untested with a proc that defines one or more productions.

I commented out the goToDefinition implementation for expanding code to individual buffer files as we only want one buffer file per workspace.

**Comment by marinier** [comment]
* tclExpansion test needs to be updated (currently fails)
* `buffer.soar` should be changed to something more unique and less likely to conflict with an actual file. E.g., `~tclExpansionBuffer.soar`
* We need an alternative to goto definition for triggering the expansion, as for a proc call we need that to go to the definition of the proc. Robert thought maybe it would be ok if we distinguished between goto definition on the name of the proc vs. its args, but there may be proc calls with no args, so that's not a general solution. Ideally it would be tied to the cursor position, but if that's not possible then maybe a custom code action could be used (hopefully with a keybinding).

**Comment by marinier** [comment]
It seems like a lot of files get re-processed on the server side on each hover. In a complex agent, it looks like all of NGS4 and more -- not sure, but it may be reprocessing everything. This makes it super slow on a large agent.

**Comment by adeschamps** [comment]
The URI of the buffer file should ideally be configurable. Adding a `String expansionsFile = "some/reasonable/default";` to the `com.soartech.soarls.Configuration` class should be all that is needed.

**Comment by adeschamps** [comment]
Regarding the reprocessing of files: I presume that the act of updating the expansion file implicitly triggers a new analysis because executing a `workspace/applyEdit` will trigger a `document/didChange` notification.

One option would be to add a condition to the `didChange` handler that specifically ignores the buffer file. Another, more general option, would be to use the result of the previous analysis to determine whether the changed file is part of the agent (basically, just check if the modified file is a key in the `ProjectAnalysis.files` map).

**Comment by adeschamps** [comment]
All the issues mentioned here have now been fixed.
