### ISSUE TITLE
Whitespace lost from proc documentation in tooltips

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#46]
If I have a proc like this:

```
# test --
#
# This is a test proc.
# It's really great.
#
# Arguments:
#    arg1            This is the first arg
#    arg2 (optional) This is the second arg
#
# Results:
#    Does stuff.
proc test { arg1 { arg2 ""} } {
}
```

When I hover over a call to it, the tooltip comes out like this:
```
test --

This is a test proc. It's really great.

Arguments: arg1 This is the first arg arg2 (optional) This is the second arg

Results: Does stuff.
```

Notice how any text not separated by a blank newline ends up together on the same line.

**Comment by adeschamps** [comment]
Unfortunately I think this is just how VSCode's tooltip rendering works. The text we send strips the leading `#` comment characters, but it includes newlines and leading spaces. (see also [this issue](https://github.com/Microsoft/vscode/issues/44953) which mentions the behaviour)

**Comment by marinier** [comment]
The linked issue seems to indicate that VSCode doesn’t think it’s an issue on their end. I actually wonder if the issue is line endings – if the wrong kind of newlines are used, they could be lost. Can we force it to \r\n for the tooltips?

**Comment by marinier** [comment]
Putting in `\r\n` didn't fix it, but putting in `\r\n\r\n` does. I'm not sure if the `\r`s are actually necessary (we should try it on a non-windows machine). I'm also not sure if this will mess things up in other IDEs. Let's discuss before I push this.

**Comment by adeschamps** [comment]
The reason `\r\n\r\n` works is because you're explicitly inserting blank lines between each line of text (`\n\n` would probably work as well). It would definitely create issues in other editors.

Personally, I would encourage developers to write their comments in proper markdown. They'll get a lot more long-term mileage out of them that way.

One option, although I don't like this idea, is to prefix each line with four spaces. This would cause markdown renderers to render the text verbatim, without being too messy for non-markdown renderers. However, I don't like this idea because it prevents you from using actual formatting inside your comments.
